"""initial schema

Revision ID: 0d39ee97cdbd
Revises: 
Create Date: 2025-12-10 03:45:07.507165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d39ee97cdbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='checkpoint | lora | vae | embedding | controlnet'),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False, comment='R2 URI (r2://bucket/key)'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True, comment='SHA256 hash'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview_url', sa.String(length=2048), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Janua user ID'),
    sa.Column('org_id', sa.UUID(), nullable=True, comment='Janua organization ID'),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Model-specific metadata (base model, triggers, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False, comment='social | video | 3d | utility'),
    sa.Column('workflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='ComfyUI workflow in API format'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for workflow inputs'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('preview_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Required model names'),
    sa.Column('vram_requirement_gb', sa.Integer(), nullable=False, comment='Minimum VRAM in GB'),
    sa.Column('fork_count', sa.Integer(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_table('workflows',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='ComfyUI workflow in API format'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for workflow inputs'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Janua user ID'),
    sa.Column('org_id', sa.UUID(), nullable=True, comment='Janua organization ID'),
    sa.Column('template_id', sa.UUID(), nullable=True, comment='Original template if forked'),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_index(op.f('ix_workflows_org_id'), 'workflows', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Janua user ID'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False, comment='0.0 to 1.0'),
    sa.Column('current_node', sa.String(length=255), nullable=True, comment='Currently executing node ID'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Input parameters for this run'),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Execution metadata (timings, vram, etc.)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='0-10, higher = more urgent'),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True, comment='URL to POST results'),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True, comment='Worker that processed this job'),
    sa.Column('gpu_seconds', sa.Float(), nullable=False),
    sa.Column('cold_start_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_jobs_workflow_id'), 'jobs', ['workflow_id'], unique=False)
    op.create_table('outputs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Janua user ID'),
    sa.Column('output_type', sa.String(length=50), nullable=False, comment='image | video | model'),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False, comment='R2 URI for full output'),
    sa.Column('thumbnail_uri', sa.String(length=2048), nullable=True, comment='R2 URI for thumbnail'),
    sa.Column('output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Output-specific metadata (dimensions, duration, etc.)'),
    sa.Column('published_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of {channel, url, published_at}'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outputs_job_id'), 'outputs', ['job_id'], unique=False)
    op.create_index(op.f('ix_outputs_user_id'), 'outputs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outputs_user_id'), table_name='outputs')
    op.drop_index(op.f('ix_outputs_job_id'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_jobs_workflow_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_org_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
