apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceq
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- studio-deployment.yaml
- studio-service.yaml
- network-policies.yaml
images:
- name: ghcr.io/madfam-org/ceq/api
  newName: ghcr.io/madfam-org/ceq/api
- name: ghcr.io/madfam-org/ceq/studio
  newName: ghcr.io/madfam-org/ceq/studio
